# Generated by Django 4.1.2 on 2022-10-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id_persona', models.AutoField(db_column='id_persona', primary_key=True, serialize=False)),
                ('tipo_id_pers', models.CharField(blank=True, db_column='tipo_id_pers', max_length=50, null=True)),
                ('identificacion_pers', models.CharField(db_column='identificacion_pers', max_length=50, unique=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('apellido', models.CharField(db_column='apellido', max_length=50)),
                ('email', models.CharField(db_column='email', max_length=50, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(db_column='celular', max_length=50)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=50, null=True)),
                ('estado_pers', models.BooleanField(db_column='estado_pers', default=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'Personas',
                'ordering': ['id_persona'],
            },
        ),
    ]
