# Generated by Django 4.1.2 on 2022-10-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='fecha_nacimiento',
            field=models.DateTimeField(),
        ),
    ]
